// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace GloboTicket.TicketManagement.Identity.CompiledModels
{
    [DbContext(typeof(GloboTicketIdentityDbContext))]
    public partial class GloboTicketIdentityDbContextModel : RuntimeModel
    {
        static GloboTicketIdentityDbContextModel()
        {
            var model = new GloboTicketIdentityDbContextModel();
            model.Initialize();
            model.Customize();
            _instance = model;
        }

        private static GloboTicketIdentityDbContextModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
