version: '3.4'

services:
  sundoecoffeeshop-admin-frontend:
    image: tsmoreland/sundoecoffeeshopadminfrontendapp:latest
    build:
      context: .
      dockerfile: src/Admin/FrontEnd/App/Dockerfile

