// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace WiredBrainCoffee.EmployeeManager.Infrastructure.CompiledModels
{
    public partial class EmployeeManagerDbContextModel
    {
        partial void Initialize()
        {
            var departmentEntity = DepartmentEntityEntityType.Create(this);
            var employeeEntity = EmployeeEntityEntityType.Create(this);

            EmployeeEntityEntityType.CreateForeignKey1(employeeEntity, departmentEntity);

            DepartmentEntityEntityType.CreateAnnotations(departmentEntity);
            EmployeeEntityEntityType.CreateAnnotations(employeeEntity);

            AddAnnotation("ProductVersion", "7.0.0");
        }
    }
}
