// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace WiredBrainCoffee.EmployeeManager.Infrastructure.CompiledModels
{
    [DbContext(typeof(EmployeeManagerDbContext))]
    public partial class EmployeeManagerDbContextModel : RuntimeModel
    {
        static EmployeeManagerDbContextModel()
        {
            var model = new EmployeeManagerDbContextModel();
            model.Initialize();
            model.Customize();
            _instance = model;
        }

        private static EmployeeManagerDbContextModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
