kind: Service
apiVersion: v1
metadata:
  name: catalog
  labels:
    app: catalog
spec:
  selector:
    app: catalog
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: http
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
  labels:
    app: catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      securityContext:
        runAsUser: 10000
        runAsGroup: 2000
        fsGroup: 2000
        runAsNonRoot: true
      containers:
      - name: catalog
        image: catalog:dev
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: CONNECTIONSTRINGS__DEFAULT
          value: Server=sqlserver;Database=EventCatalogDb;User=sa;pwd=P@ssW0rd!;MultipleActiveResultSets=true
        ports:
        - containerPort: 8080
        imagePullPolicy: Never
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - all
