kind: Service
apiVersion: v1
metadata:
  name: ordering
  labels:
    app: ordering
spec:
  selector:
    app: ordering
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: http
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordering
  labels:
    app: ordering
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ordering
  template:
    metadata:
      labels:
        app: ordering
    spec:
      securityContext:
        runAsUser: 10000
        runAsGroup: 2000
        fsGroup: 2000
        runAsNonRoot: true
      containers:
      - name: ordering
        image: ordering:dev
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        ports:
        - containerPort: 8080
        imagePullPolicy: Never
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - all

