// <auto-generated />
using System;
using CarInventory.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarInventory.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CarsDbContext))]
    partial class CarsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("CarInventory.Domain.Models.Car", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<double>("CurrentFuel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0)
                        .HasColumnName("current_fuel");

                    b.Property<int>("Engine")
                        .HasColumnType("INTEGER")
                        .HasColumnName("engine_type");

                    b.Property<double>("FuelCapacityInLitres")
                        .HasColumnType("REAL")
                        .HasColumnName("fuel_capacity");

                    b.Property<int>("HorsePower")
                        .HasColumnType("INTEGER")
                        .HasColumnName("horse_power");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .HasColumnName("make");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .HasColumnName("model");

                    b.Property<double>("MpG")
                        .HasColumnType("REAL")
                        .HasColumnName("mpg");

                    b.Property<int>("NumberOfDoors")
                        .HasColumnType("INTEGER")
                        .HasColumnName("number_of_doors");

                    b.HasKey("Id");

                    b.HasIndex("Make", "Model")
                        .IsUnique();

                    b.ToTable("cars", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
