version: '3.4'

services:
  frontend-mvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ApiConfigs__ConcertCatalog__Uri=http://catalog
      - ApiConfigs:Ordering:Uri=http://ordering
    ports:
      - "8088:80"
      - "4433:443"
    expose:
      - "8088"
      - "4433"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  catalog:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - CONNECTIONSTRINGS__DEFAULT=Server=sqlserver;Database=concertDB;User Id=sa;Password=P@55w0Rd!;MultipleActiveResultSets=True;TrustServerCertificate=true;
    ports:
      - "80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  ordering:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=TRUE
      - MSSQL_SA_PASSWORD=P@55w0Rd!  

