// <auto-generated />

using MicroShop.Services.Products.App.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MicroShop.Services.Products.App.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240329142729_AddImageLocalPath")]
    partial class AddImageLocalPath
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MicroShop.Services.Products.App.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageLocalPath")
                        .HasMaxLength(260)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NormalizedCategoryName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedCategoryName");

                    b.HasIndex("NormalizedName");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Electronics",
                            Description = "Travel light and stay rugged without sacrificing an inch of speed and power with the smart, slim, lightweight, and military-grade durable IdeaPad Slim 5",
                            ImageUrl = "https://m.media-amazon.com/images/W/AVIF_800250-T3/images/I/71j4CpWJMHL._AC_SX425_.jpg",
                            Name = "Lenovo IdeaPad Slim 5",
                            NormalizedCategoryName = "ELECTRONICS",
                            NormalizedName = "LENOVO IDEAPAD SLIM 5",
                            Price = 549.99000000000001
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Electronics",
                            Description = "SUPERCHARGED BY M3 PRO OR M3 MAX — The Apple M3 Pro chip, with an up to 12-core CPU and up to 18-core GPU",
                            ImageUrl = "https://m.media-amazon.com/images/W/AVIF_800250-T3/images/I/61RnQM+JDTL._AC_SX679_.jpg",
                            Name = "Apple 2023 MacBook Pro laptop M3 Pro",
                            NormalizedCategoryName = "ELECTRONICS",
                            NormalizedName = "APPLE 2023 MACBOOK PRO LAPTOP M3 PRO",
                            Price = 1899.97
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Electronics",
                            Description = "16-inch high-performance gaming laptop with the latest CPU and GPU offerings",
                            ImageUrl = "https://m.media-amazon.com/images/W/AVIF_800250-T3/images/I/81FV-rLoN8L._AC_SX425_.jpg",
                            Name = "Alienware M16 Gaming Laptop - 16-inch",
                            NormalizedCategoryName = "ELECTRONICS",
                            NormalizedName = "ALIENWARE M16 GAMING LAPTOP - 16-INCH",
                            Price = 2729.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
