// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WiredBrainCoffee.EmployeeManager.Infrastructure;

#nullable disable

namespace WiredBrainCoffee.EmployeeManager.Infrastructure.Migrations
{
    [DbContext(typeof(EmployeeManagerDbContext))]
    [Migration("20221204020138_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("WiredBrainCoffee.EmployeeManager.Infrastructure.Entities.DepartmentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastModifiedTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<ulong>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LastModifiedTime = 0L,
                            Name = "Finance",
                            Version = 0ul
                        },
                        new
                        {
                            Id = 2,
                            LastModifiedTime = 0L,
                            Name = "Sales",
                            Version = 0ul
                        },
                        new
                        {
                            Id = 3,
                            LastModifiedTime = 0L,
                            Name = "Marketing",
                            Version = 0ul
                        },
                        new
                        {
                            Id = 4,
                            LastModifiedTime = 0L,
                            Name = "HR",
                            Version = 0ul
                        },
                        new
                        {
                            Id = 5,
                            LastModifiedTime = 0L,
                            Name = "IT",
                            Version = 0ul
                        },
                        new
                        {
                            Id = 6,
                            LastModifiedTime = 0L,
                            Name = "Research and Development",
                            Version = 0ul
                        });
                });

            modelBuilder.Entity("WiredBrainCoffee.EmployeeManager.Infrastructure.Entities.EmployeeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeveloper")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<long>("LastModifiedTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<ulong>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            FirstName = "John",
                            IsDeveloper = false,
                            LastModifiedTime = 0L,
                            LastName = "Smith",
                            Version = 0ul
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 2,
                            FirstName = "Jessica",
                            IsDeveloper = false,
                            LastModifiedTime = 0L,
                            LastName = "Jones",
                            Version = 0ul
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 3,
                            FirstName = "Tony",
                            IsDeveloper = true,
                            LastModifiedTime = 0L,
                            LastName = "Stark",
                            Version = 0ul
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 4,
                            FirstName = "Edward",
                            IsDeveloper = false,
                            LastModifiedTime = 0L,
                            LastName = "Enigma",
                            Version = 0ul
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 5,
                            FirstName = "Brenda",
                            IsDeveloper = false,
                            LastModifiedTime = 0L,
                            LastName = "Moore",
                            Version = 0ul
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 6,
                            FirstName = "Bruce",
                            IsDeveloper = true,
                            LastModifiedTime = 0L,
                            LastName = "Wayne",
                            Version = 0ul
                        });
                });

            modelBuilder.Entity("WiredBrainCoffee.EmployeeManager.Infrastructure.Entities.EmployeeEntity", b =>
                {
                    b.HasOne("WiredBrainCoffee.EmployeeManager.Infrastructure.Entities.DepartmentEntity", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("WiredBrainCoffee.EmployeeManager.Infrastructure.Entities.DepartmentEntity", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
