// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace GloboTicket.Shop.Catalog.Infrastructure.Persistence.CompiledModels
{
    public partial class EventCatalogDbContextModel
    {
        partial void Initialize()
        {
            var concert = ConcertEntityType.Create(this);
            var auditDetails = AuditDetailsEntityType.Create(this);

            AuditDetailsEntityType.CreateForeignKey1(auditDetails, concert);

            ConcertEntityType.CreateAnnotations(concert);
            AuditDetailsEntityType.CreateAnnotations(auditDetails);

            AddAnnotation("ProductVersion", "7.0.2");
            AddAnnotation("Relational:MaxIdentifierLength", 128);
            AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
        }
    }
}
