version: '3.8'

services:
  localstack:
    container_name: "localstack"
    image: localstack/localstack:1.4.0
    ports:
      - "127.0.0.1:4510-4559:4510-4559"
      - "127.0.0.1:4566:4566"
    environment:
      SERVICES: "sqs,sns,s3,cloudformation"
      DEBUG: false
      DOCKER_HOST: unix:///var/run/docker.sock
    volumes:
      - /var/lib/localstack:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock